language: python

services:
  - docker

before_install:
  - docker build -t fedora-websites .
  - docker run -it --rm -v "$(pwd):/opt/:z" fedora-websites ./scripts/pull-translations.sh

script:
  - docker run -it --rm -v "$(pwd):/opt/:z" fedora-websites python main.py
