language: python

services:
  - docker

before_install:
  - docker build -t fedora-websites .
  - docker run -it --rm -v "$(pwd):/opt/:z" fedora-websites ./scripts/pull-translations.sh
  - docker run -it --rm -v "$(pwd):/opt/:z" fedora-websites python ./scripts/pull-magazine.py

script:
  - docker run -it --rm -v "$(pwd):/opt/:z" fedora-websites python main.py

# Just notify #relrodtest for now, maybe make this #fedora-websites at some
# point if it works out and isn't too annoying
notifications:
  webhooks:
    if: type != cron
    urls:
      - https://sl.da.gd/travisci?channel=%23relrodtest
