---
name: Fedora Websites
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 0 12 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2

      - name: Build site
        run: |
          docker build -t fedora-websites .
          docker run --rm -v "$(pwd):/opt/:z" fedora-websites ./scripts/pull-translations.sh
          docker run --rm -v "$(pwd):/opt/:z" fedora-websites python3 ./scripts/pull-magazine.py
          docker run --rm -v "$(pwd):/opt/:z" fedora-websites python3 main.py
